config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "home#index"
  
  namespace :admin do 
    root to: "home#index"
    resources :articles do
      member do
        get 'year'
      end
      collection do
        get 'published'
        get 'banned'
        get 'publish'
        get 'ban'
      end
    end

    resources :columns
    resources :channels do
      collection do
        post 'add_column'
      end
    end
    resources :blogrolls
  end
  resources :articles,only: [:index,:show]
  resources :sessions,only: [:new,:create,:destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :columns,only: [:show]
  resources :search,only: [:index]

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :digest, :publisher, :state, :title

  has_many :articlecolumnships
  has_many :columns,:through => :articlecolumnships

  validates_presence_of :title,:digest,:publisher
  
  scope :draft,where(state: "draft")
  scope :published,where(state: "published")
  scope :banned,where(state: "banned")


  default_scope :order => 'created_at DESC'

  searchable do
		text :title, :digest  	
  end

end

app/controllers/admin/articles_controller.rb
#encoding:utf-8
class Admin::ArticlesController < AdminController
	before_filter :find_article,only: [:show,:edit,:update,:destroy,:publish,:ban]

	#draft articles
	def index
		@articles = Article.draft.page(params[:page]).per(10)
	end

	#published articles
	def published
		@articles = Article.published.page(params[:page]).per(10)
	end

	#banned articles
  def banned
  	@articles = Article.banned.page(params[:page]).per(10)
  end

	def new
		@article = Article.new
		#@article.articlecolumnships.build(:article_id => @article.id).build_column
	end

	def show
	end

	def create
		# render json: params[:article]
		columns = Array.new
		columns = params[:articlecolumnship][:column_id]
		columns.shift
		params[:articlecolumnship][:column_id] = nil
		@article = Article.new(params[:article])
    
		if @article.save
			columns.each {|c|
    	    Articlecolumnship.create(article_id: @article.id,column_id: c.to_i) 	
      }

			redirect_to admin_articles_path,notice: "添加成功."
		else
			redirect_to admin_articles_path,alert: "添加失败."
		end
	end

	def edit
	end

	def update
				
		columns = Array.new
		columns = params[:articlecolumnship][:column_id]
		columns.shift
		if !columns.empty?	
			@articlecolumnships=@article.articlecolumnships
			@articlecolumnships.each {|a| a.delete}
			columns.each {|c|
	    	Articlecolumnship.create(article_id: @article.id,column_id: c.to_i) ;  	
	     }
	  end

		if @article.update_attributes(params[:article])
			 redirect_to admin_articles_path,notice: "更新成功."
		else
			 redirect_to admin_articles_path,alert: "更新失败."
		end

	end

	def destroy
		@article.delete
		redirect_to admin_articles_path,notice: "删除成功."
	end

	#发布
	def publish
		@article.state = "published"
		if @article.update_attributes(params[:article])
			redirect_to published_admin_articles_path,notice: "发布成功."
		else
			redirect_to published_admin_articles_path,alert: "发布失败."
		end
	end

	#禁止
	def ban
		@article.state = "banned"
		if @article.update_attributes(params[:article])
			redirect_to banned_admin_articles_path,notice: "您已禁止发布此文章."
		else
			redirect_to banned_admin_articles_path,alert: "禁止失败."
		end
	end

	private
	def find_article
		@article = Article.find(params[:id])
	end

end

app/controllers/articles_controller.rb
#encoding:utf-8
class ArticlesController < ApplicationController
	def index
	end

	def show
		@article = Article.find(params[:id])
	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/admin/articles/banned.slim
h4
  i.icon-list-alt
  span.text-info =t('system.banned')
  = link_to "添加文章",new_admin_article_path, class: "pull-right"
table class="table table-bordered table-hover"
  thead
    tr
      th.index_number 序号
      th 标题
      th 发布人
      th 归属栏目
      th 创建时间
      th 审核状态 
      th 操作
  tbody
    - @articles.each_with_index do |article,index|
      tr
        td = index = index+1 
        td = link_to article.title,admin_article_path(article),title: "#{article.title}"              
        td = article.publisher
        td 
           - article.columns.each do |c|
             = c.title
             '&nbsp;
        td = article.created_at().strftime('%Y-%m-%d %H:%M:%S')
        td = article.state
        td 
           = link_to "发布",publish_admin_articles_path(:id => article.id)
           ||
           = link_to "编辑",edit_admin_article_path(article)
           ||
           = link_to "删除", admin_article_path(article) , method: :delete, data: { confirm: '确定此操作吗？' } 
.pagination.pagination-centered
  = paginate @articles

app/views/admin/articles/edit.slim
= form_for(@article,as: :article,url: admin_article_path(@article)) do |f|
  = f.label :title
  = f.text_field :title
  = f.label :publisher
  = f.text_field :publisher
  = fields_for :articlecolumnship do |ac|
    = ac.label "归属栏目(不该变则不选)"
    = ac.select :column_id,Column.all.map { |c| [c.title, c.id] },
						  {include_blank: false},
						  { class: 'chosen-select',multiple: "true" }
  = f.hidden_field :state
  = f.label :digest
  = f.cktext_area :digest
  br
  = f.submit "更新文章",class: "btn"

app/views/admin/articles/index.slim
h4
  i.icon-list-alt
  span.text-info =t('system.draft')
  = link_to "添加文章",new_admin_article_path, class: "pull-right"
table class="table table-bordered table-hover"
  thead
    tr
      th.index_number 序号
      th 标题
      th 发布人
      th 归属栏目
      th 创建时间
      th 审核状态 
      th 操作
  tbody
    - @articles.each_with_index do |article,index|
      tr
        td = index = index+1 
        td = link_to article.title,admin_article_path(article),title: "#{article.title}"              
        td = article.publisher
        td 
           - article.columns.each do |c|
             = c.title
             '&nbsp;
        td = article.created_at().strftime('%Y-%m-%d %H:%M:%S')
        td = article.state
        td 
           = link_to "发布",publish_admin_articles_path(:id => article.id)
           ||
           = link_to "禁止",ban_admin_articles_path(:id => article.id)
           ||
           = link_to "编辑",edit_admin_article_path(article)
           ||
           = link_to "删除", admin_article_path(article) , method: :delete, data: { confirm: '确定此操作吗？' } 
.pagination.pagination-centered
  = paginate @articles

app/views/admin/articles/new.html.erb
<%= form_for(@article,as: :article, :validate => true,url: admin_articles_path) do |f| %>
  <p>
  <%= f.label :title%>
  <%= f.text_field :title, :validate => true%>
  </p>
  <p>
  <%= f.label :publisher%>
  <%= f.text_field :publisher%>
  </p>
  <p>
  <%= fields_for :articlecolumnship do |ac| %>
    <%= ac.label "*归属栏目"%>
    <%= ac.select :column_id,Column.all.map { |c| [c.title, c.id] },
						  {include_blank: false},
						  { class: 'chosen-select',multiple: "true" }%>
  <% end %>
  </p>
  <%= f.hidden_field :state%>
  <p>
  <%= f.label :digest%>
  <%= f.cktext_area :digest%>
  </p>
  <br>
  <%= f.submit "新建文章",class: "btn"%>
<% end %>

app/views/admin/articles/published.slim
h4
  i.icon-list-alt
  span.text-info =t('system.published')
  = link_to "添加文章",new_admin_article_path, class: "pull-right"
table class="table table-bordered table-hover"
  thead
    tr
      th.index_number 序号
      th 标题
      th 发布人
      th 归属栏目
      th 创建时间
      th 审核状态 
      th 操作
  tbody
    - @articles.each_with_index do |article,index|
      tr
        td = index = index+1 
        td = link_to article.title,admin_article_path(article),title: "#{article.title}"              
        td = article.publisher
        td 
           - article.columns.each do |c|
             = c.title
             '&nbsp;
        td = article.created_at().strftime('%Y-%m-%d %H:%M:%S')
        td = article.state
        td 
           = link_to "禁止",ban_admin_articles_path(:id => article.id)
           ||
           = link_to "编辑",edit_admin_article_path(article)
           ||
           = link_to "删除", admin_article_path(article) , method: :delete, data: { confirm: '确定此操作吗？' } 
.pagination.pagination-centered
  = paginate @articles

app/views/admin/articles/show.slim
br
h3 align="center" #{@article.title}
p align="center" 
  |
  a> href="http://www.nbd.com.cn" http://www.nbd.com.cn
  | &nbsp;&nbsp;&nbsp;&nbsp;#{@article.created_at.strftime('%Y-%m-%d %H:%M')}
.contain 
  = @article.digest.html_safe
  hr
.contain
  ul
    p 
      .pull-right 
        '发布人：#{@article.publisher}
      |
      '归类于:&nbsp;&nbsp;
      - @article.columns.each do |c|
        = link_to c.title,"#"
        '&nbsp;&nbsp;
     
br
br