config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "home#index"
  
  namespace :admin do 
    root to: "home#index"
    resources :articles do
      member do
        get 'year'
      end
      collection do
        get 'published'
        get 'banned'
        get 'publish'
        get 'ban'
      end
    end

    resources :columns
    resources :channels do
      collection do
        post 'add_column'
      end
    end
    resources :blogrolls
  end
  resources :articles,only: [:index,:show]
  resources :sessions,only: [:new,:create,:destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :columns,only: [:show]
  resources :search,only: [:index]

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :digest, :publisher, :state, :title

  has_many :articlecolumnships
  has_many :columns,:through => :articlecolumnships

  validates_presence_of :title,:digest,:publisher
  
  scope :draft,where(state: "draft")
  scope :published,where(state: "published")
  scope :banned,where(state: "banned")


  default_scope :order => 'created_at DESC'

  searchable do
		text :title, :digest  	
  end

end

app/models/articlecolumnship.rb
class Articlecolumnship < ActiveRecord::Base
  attr_accessible :article_id, :column_id

  belongs_to :article
  belongs_to :column

  #accepts_nested_attributes_for :column
end

app/models/blogroll.rb
class Blogroll < ActiveRecord::Base
  attr_accessible :title, :url
  validates_presence_of :title,:url
  validates_format_of :url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix,message: "URL格式不正确"
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :link_str, :title

  has_many :columns

  validates_presence_of :title,:link_str
  validates_format_of :link_str, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix,message: "URL格式不正确"
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset

  # has_attached_file :data,
  #                   :url => "/ckeditor_assets/attachments/:id/:filename",
  #                   :path => ":rails_root/public/ckeditor_assets/attachments/:id/:filename"
  
  #validates_attachment_size :data, :less_than => 100.megabytes
  #validates_attachment_presence :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  # has_attached_file :data,
  #                   :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
  #                   :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
  #                   :styles => { :content => '800>', :thumb => '118x100#' }

  # validates_attachment_size :data, :less_than => 2.megabytes
  # validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/column.rb
class Column < ActiveRecord::Base
  attr_accessible :title,:channel_id

 belongs_to :channel
 has_many :articlecolumnships
 has_many :articles,:through => :articlecolumnships

 validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :hashed_password, :login, :salt

  validates :login, :presence => true

  def password
  	@password
  end

  def password=(pass)
  	return unless pass
	  @password=pass
	  generate_password(pass)
  end

  def authentication(user,password)
    if Digest::SHA256.hexdigest(password + user.salt)==user.hashed_password
      return true
    end
    false
  end

  private 
  def generate_password(pass)
  	self.salt = Array.new(10){rand(1024).to_s(36)}.join
    self.hashed_password = Digest::SHA256.hexdigest(pass+salt)
  end

end

app/controllers/admin/channels_controller.rb
#encoding:utf-8
class Admin::ChannelsController < AdminController
	before_filter :find_channel,only: [:edit,:update,:destroy]
	
	def index
		@channels = Channel.order(:title).page(params[:page]).per(10)
		@columns = Column.all
		#render json: Channel.last.columns
	end

	def new
		@channel = Channel.new
	end

	def create
		@channel = Channel.new(params[:channel])
		if @channel.save
			redirect_to admin_channels_path,notice: "添加成功."
		else
			redirect_to admin_channels_path,alert: "添加失败."
		end
	end

	def edit
	end

	def update
		#render json: params[:channel][:tag_list]
		#@channel.tag_list = params[:channel][:tag_list]
		if @channel.update_attributes(params[:channel])
			redirect_to admin_channels_path,notice: "更新成功."
		else
			redirect_to admin_channels_path,alert: "更新失败."
		end
	end

	def destroy
		@channel.delete
		redirect_to admin_channels_path,notice: "删除成功."
	end

	def add_column
		#render json: params[:column][:title]

		#redirect_to admin_channels_path,alert: "更新失败."
	end

	private
	def find_channel
		@channel = Channel.find(params[:id])
	end

end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user

  def authenticate_user
    if current_user.nil?
      flash[:alert] = t('devise.failure.unauthenticated')
      redirect_to signin_url
    end
  end

  def current_user
    # Note: we want to use "find_by_id" because it's OK to return a nil.
    # If we were to use User.find, it would throw an exception if the user can't be found.
    #render json: session[:user_id]
    @current_user ||= User.where(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :find_blogrolls
  protect_from_forgery

  def find_blogrolls
  	@blogrolls = Blogroll.all
  	@channels = Channel.all
  	@columns = Column.all
  end
end

app/controllers/articles_controller.rb
#encoding:utf-8
class ArticlesController < ApplicationController
	def index
	end

	def show
		@article = Article.find(params[:id])
	end

end

app/controllers/columns_controller.rb
#encoding:utf-8
class ColumnsController < ApplicationController
	
	def show
		#@article = Article.find(params[:id])
		#@articles = Article.all
		@column = Column.find(params[:id])
		@articles = @column.articles.published.page(params[:page]).per(3)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@articles = Article.published.page(params[:page]).per(3)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	#search
	def index
		@search = Article.search do 
			fulltext params[:search]
		end
		@articles = @search.results
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	layout "login"
	before_filter :login_exist?, only: [:create] 
	

	#登录
	def new

	end

	#sign up
	def create	 	
		user = User.find_by_login(params[:session][:login])
		if user && user.authentication(user,params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = t('devise.sessions.signed_in')
			redirect_to admin_root_path
		else
			flash[:alert] = t('devise.failure.invalid')
		    redirect_to signin_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:alert] = t('devise.sessions.signed_out')
		redirect_to signin_path
	end

	private
	def login_exist?
		redirect_to signin_path,alert: t('devise.failure.invalid') unless User.where(login: params[:session][:login]).exists?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def split_column(arg)
		arg.split(' ')
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/channels/_add_channel.slim
div id="newChannel" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  div class="modal-header"
    button type="button" class="close" data-dismiss="modal" aria-hidden="true" ×
    h3 id="myModalLabel" 添加频道
  div class="modal-body"
    .span4
      = form_for @channel,as: :channel,:validate => true,url: admin_channels_path,as: :post do |f|
        = f.label "频道名称"
        = f.text_field :title
        = f.label "URL链接"
        = f.text_field :link_str
        = f.submit "新建" ,class: "btn btn-primary"

app/views/admin/channels/_add_column.slim
div id="newColumn" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"
  div class="modal-header"
    button type="button" class="close" data-dismiss="modal" aria-hidden="true" ×
    h3 id="myModalLabel" 添加栏目
  div class="modal-body"
    .span4
      = form_for :column,url: admin_columns_path,as: :post do |f|
        = f.label "栏目名称"
        = f.text_field :title
        = f.submit "新建" ,class: "btn btn-primary"

app/views/admin/channels/edit.slim
= simple_form_for @channel,url: admin_channel_path(@channel) do |f|
  = f.input :title
  = f.input :link_str
  br
  = f.submit "更新",class: "btn"

app/views/admin/channels/index.slim
h4
  i.icon-list-alt
  span.text-info =t('system.channel')
  a href="#newChannel" data-toggle="modal" class="pull-right" 添加频道
table class="table table-bordered table-hover"
  thead
    tr
      th.index_number 序号
      th 频道名称
      th.span3 URL链接
      th 包含栏目
      th 操作
  tbody
    - @channels.each_with_index do |channel,index|
      tr
        td = index=index+1
        td = channel.title
        td = link_to channel.link_str,channel.link_str,target: "_blank"
        td 
          - if channel.columns.empty?
            = "暂无"
          - channel.columns.each do |column|
            = column.title
            '&nbsp;&nbsp;
        td 
          = link_to "编辑", edit_admin_channel_path(id: channel.id)
          ||
          = link_to "删除", admin_channel_path(channel) , method: :delete, data: { confirm: '确定此操作吗？' } 
.pagination.pagination-centered
  = paginate @channels      
= render 'add_channel'
= render 'add_column'

app/views/admin/channels/new.slim
= form_for @channel,as: :channel,:validate => true,url: admin_channels_path(@channel) do |f|
  = f.label :title
  = f.text_field :title
  = f.label :link_str
  = f.text_field :link_str
  br
  = f.submit "新建频道",class: "btn"