config/routes.rb
Blog::Application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  root to: "home#index"
  
  namespace :admin do 
    root to: "home#index"
    resources :articles do
      member do
        get 'year'
      end
      collection do
        get 'published'
        get 'banned'
        get 'publish'
        get 'ban'
      end
    end

    resources :columns
    resources :channels do
      collection do
        post 'add_column'
      end
    end
    resources :blogrolls
  end
  resources :articles,only: [:index,:show]
  resources :sessions,only: [:new,:create,:destroy]
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  resources :columns,only: [:show]
  resources :search,only: [:index]

end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :digest, :publisher, :state, :title

  has_many :articlecolumnships
  has_many :columns,:through => :articlecolumnships

  validates_presence_of :title,:digest,:publisher
  
  scope :draft,where(state: "draft")
  scope :published,where(state: "published")
  scope :banned,where(state: "banned")


  default_scope :order => 'created_at DESC'

  searchable do
		text :title, :digest  	
  end

end

app/models/articlecolumnship.rb
class Articlecolumnship < ActiveRecord::Base
  attr_accessible :article_id, :column_id

  belongs_to :article
  belongs_to :column

  #accepts_nested_attributes_for :column
end

app/models/blogroll.rb
class Blogroll < ActiveRecord::Base
  attr_accessible :title, :url
  validates_presence_of :title,:url
  validates_format_of :url, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix,message: "URL格式不正确"
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :link_str, :title

  has_many :columns

  validates_presence_of :title,:link_str
  validates_format_of :link_str, :with => /^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(:[0-9]{1,5})?(\/.*)?$/ix,message: "URL格式不正确"
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  # has_attached_file :data,
  #                   :url  => "/ckeditor_assets/pictures/:id/:style_:basename.:extension",
  #                   :path => ":rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension",
  #                   :styles => { :content => '800>', :thumb => '118x100#' }

  # validates_attachment_size :data, :less_than => 2.megabytes
  # validates_attachment_presence :data

  def url_content
    url(:content)
  end
end

app/models/column.rb
class Column < ActiveRecord::Base
  attr_accessible :title,:channel_id

 belongs_to :channel
 has_many :articlecolumnships
 has_many :articles,:through => :articlecolumnships

 validates_presence_of :title
end

app/models/user.rb
class User < ActiveRecord::Base
  #attr_accessible :hashed_password, :login, :salt

  validates :login, :presence => true

  def password
  	@password
  end

  def password=(pass)
  	return unless pass
	  @password=pass
	  generate_password(pass)
  end

  def authentication(user,password)
    if Digest::SHA256.hexdigest(password + user.salt)==user.hashed_password
      return true
    end
    false
  end

  private 
  def generate_password(pass)
  	self.salt = Array.new(10){rand(1024).to_s(36)}.join
    self.hashed_password = Digest::SHA256.hexdigest(pass+salt)
  end

end

app/controllers/admin_controller.rb
class AdminController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_user

  def authenticate_user
    if current_user.nil?
      flash[:alert] = t('devise.failure.unauthenticated')
      redirect_to signin_url
    end
  end

  def current_user
    # Note: we want to use "find_by_id" because it's OK to return a nil.
    # If we were to use User.find, it would throw an exception if the user can't be found.
    #render json: session[:user_id]
    @current_user ||= User.where(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_filter :find_blogrolls
  protect_from_forgery

  def find_blogrolls
  	@blogrolls = Blogroll.all
  	@channels = Channel.all
  	@columns = Column.all
  end
end

app/controllers/articles_controller.rb
#encoding:utf-8
class ArticlesController < ApplicationController
	def index
	end

	def show
		@article = Article.find(params[:id])
	end

end

app/controllers/columns_controller.rb
#encoding:utf-8
class ColumnsController < ApplicationController
	
	def show
		#@article = Article.find(params[:id])
		#@articles = Article.all
		@column = Column.find(params[:id])
		@articles = @column.articles.published.page(params[:page]).per(3)
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@articles = Article.published.page(params[:page]).per(3)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	#search
	def index
		@search = Article.search do 
			fulltext params[:search]
		end
		@articles = @search.results
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	layout "login"
	before_filter :login_exist?, only: [:create] 
	

	#登录
	def new

	end

	#sign up
	def create	 	
		user = User.find_by_login(params[:session][:login])
		if user && user.authentication(user,params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = t('devise.sessions.signed_in')
			redirect_to admin_root_path
		else
			flash[:alert] = t('devise.failure.invalid')
		    redirect_to signin_path
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:alert] = t('devise.sessions.signed_out')
		redirect_to signin_path
	end

	private
	def login_exist?
		redirect_to signin_path,alert: t('devise.failure.invalid') unless User.where(login: params[:session][:login]).exists?
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def split_column(arg)
		arg.split(' ')
	end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.slim
.footer_nav
  - @blogrolls.each_with_index do |blogroll,index|
    - index=index+1
    - if index==1
      = link_to blogroll.title,blogroll.url,class: "first"
    - else
      = link_to blogroll.title,blogroll.url
p Copyright © 2013 版权没有，可在github上查看源代码，欢迎指错和修改，违者不究。  —  by 丁历祥.

app/views/layouts/_header.slim
- @channels.each do |channel|
  .nav_item
    dl
	    dt
	      a> href="#{channel.link_str}" target="_blank" #{channel.title} 
	      - channel.columns.each do |i|
	        dd
	          = link_to i.title,column_path(i)

app/views/layouts/admin.slim
doctype html
html
  head
    title= t('system.title') 
    link rel="shortcut icon" href="http://static.nbd.com.cn/favicon.ico" type="image/x-icon"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body#body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          .span12.pull-left
            span.brand.pull-left
              i.icon-home
              a href= admin_root_path title="回首页"
                strong.text-info=t('system.title')
            span.divider-vertical
              ul class="nav nav-tabs nav-pills"
                li = link_to '草稿箱',admin_articles_path
                li = link_to '已发布',published_admin_articles_path
                li = link_to '垃圾箱',banned_admin_articles_path
                li = link_to '频道',admin_channels_path
                li = link_to '栏目',admin_columns_path
                li = link_to '友情链接',admin_blogrolls_path
              ul class="nav pull-right" 
                li = link_to '写文章',new_admin_article_path
                li = link_to '网站首页',root_path
                li = link_to '退出',signout_path,:method => 'delete',:class => 'pull-right'                  
    .container style="margin-top:60px;"
      .container-fluid
        .row-fluid
          - if flash[:notice]
            .alert.alert-success
              a> href="#" class="close" data-dismiss="alert" &times;
              = flash[:notice]
          - if flash[:alert]
            .alert
              a> href="#" class="close" data-dismiss="alert" &times;
              = flash[:alert]
          = yield
      .footer
        p.pull-right
          a href="#" 回到顶端
        p
          |Copyright by 丁历祥 | &copy; 2013 

app/views/layouts/application.slim
doctype html
html
  head
    title= t('system.title') 
    link rel="shortcut icon" href="http://static.nbd.com.cn/favicon.ico" type="image/x-icon"
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body#ibody
    .header
      .header_bg
      .innerCenter
        .ad_header
          .input-append
            = form_tag search_index_path,:method => :get do
              = text_field_tag :search,params[:search],class: "span3" ,id: "appendedInputButton",placeholder: "请输入关键词..." 
              = submit_tag "搜索",:title =>nil,class: "btn"
        a> class="logo-stock" href= root_path title="股票频道首页"
        .nav1
          = render 'layouts/header'
    .wrapper
      .innerCenter
        = yield
    .footer1
      = render 'layouts/footer'

app/views/layouts/login.slim
doctype html
html
  head
    title= t('system.title') 
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  body#body
    .container style="margin-top:30px;"
      .container-fluid
        .row-fluid
          .span12
            - if flash[:notice]
              .alert.alert-success
                a> href="#" class="close" data-dismiss="alert" &times;
                = flash[:notice]
            - if flash[:alert]
              .alert
                a> href="#" class="close" data-dismiss="alert" &times;
                = flash[:alert]
            = yield
      .footer
        p.pull-right
          |艺术教学实验中心 | &copy; 2013 